# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_foreignmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySecondModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
