# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_mysecondmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysecondmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
